<template>
  <div class="wrapper">
    <ul class="content">
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
      <li>ss</li>
    </ul>
  </div>
</template>

<script>
import BScroll from 'better-scroll'
  export default {
    name: "Category",
    data(){
      return{
        scroll:null
      }
    },
    created(){},
    mounted(){
      this.scroll=new BScroll(document.querySelector('.wrapper'),{
        probeType:3,
        pullUpLoad:true
      });
      this.scroll.on('scroll',(position)=>{
        console.log(position);
      })
      this.scroll.on('pullingUp',()=>{
        console.log('11111111111111111111111111111111111');
      })
    }
  }
</script>

<style scoped>
.wrapper {
  height: 300px;
  background-color: skyblue;
  overflow: hidden;
}
</style>
